apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  # "name" is the name of the ClusterRole
  name: cluster-wide-full-access
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"]
