apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cluster-wide-full-access-binding
subjects:
- kind: User
  name: "3316ccdd-2900-446e-be87-937fe81f6206"
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: cluster-wide-full-access
  apiGroup: rbac.authorization.k8s.io
