apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: user-full-access-binding
  namespace: default
subjects:
- kind: User
  name: "3316ccdd-2900-446e-be87-937fe81f6206"
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: user-full-access
  apiGroup: rbac.authorization.k8s.io
