apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: azure-wizard-kv
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    keyvaultName: "wizard-practice-keyvault"
    objects:  |
      array:
        - |
          objectName: "wizard-practice-cert"
          objectType: "cert"
          objectVersion: ""
    tenantId: "56ce1aff-9737-4d6b-b1e6-895852be105b"
